---
title: "Visualisations"
output: html_notebook
---

```{r}
library(tidyverse)
library(usmap)
```


```{r}
source(file = "cleaning_script.R")
```

```{r}
loans_clean_viz %>% 
  group_by(sub_grade, loan_paid_flag) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = sub_grade, y = prop, fill = loan_paid_flag))+
  geom_col(width = 0.9, just = 0.5) +
  coord_flip() +
  theme_minimal() +
  labs(
    x = "Grade\n",
    y = "\nProportion",
    fill = "Was the loan paid?",
    title = "Proportion of Loans Paid by each Creditworthiness Grade\n"
  ) +
  theme(
    text = element_text(size = 12)
  ) +
  scale_fill_manual(
    values = c("#ef4123", "#002a4e")
  )

```


```{r}
loans_clean_viz %>% 
  group_by(sub_grade, issue_d) %>% 
  summarise(mean_int_rate = mean(int_rate)) %>% 
  ggplot(aes(x = issue_d, y = mean_int_rate, colour = sub_grade)) +
  geom_line(size = 1.1) +
  theme_minimal(
  ) +
  labs(x = "\nIssue Date",
       y = "Interest Rate\n",
       colour = "Grade",
       title = "Interest Rate by Issue Date of Loan") + 
  theme(
   text = element_text(size = 14)
  ) 
```

```{r}
loans_clean_viz %>% 
  group_by(issue_d, loan_paid_flag) %>% 
  summarise(count = n()) %>% 
  ggplot()+
  aes(x = issue_d, y = count, colour = loan_paid_flag) +
  geom_line(size = 1.5) +
  theme_minimal() +
  theme(
    text = element_text(size = 16)
  ) +
  labs(
    x = "\nDate",
    y = "Count\n",
    colour = "Was the loan paid?",
    title = "Number of Loans Paid by Issue Date of Loan\n"
  ) +
  scale_colour_manual(
    values = c("#ef4123", "#002a4e")
  )
```




```{r}
loans_clean_viz$emp_length <- factor(loans_clean_viz$emp_length, 
                                     levels = c("0-2 years", "3-5 years", "6-9 years", "10+ years"))

loans_clean_viz %>% 
  group_by(emp_length, loan_paid_flag) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = emp_length, y = prop, fill = loan_paid_flag))+
  geom_col() +
  coord_flip()
```




```{r}
loans_clean_viz %>% 
  group_by(loan_paid_flag) %>% 
  ggplot(aes(x = log10(annual_inc), y = stat(density), fill = loan_paid_flag))+
  geom_histogram() +
  facet_wrap(~loan_paid_flag) +
  theme_minimal()+
  theme(
    text = element_text(size = 14)
  ) +
  labs(
    x = "\nAnnual Income (log10)",
    y = "Density\n",
    title = "Distribution of Annual Incomes by Loan Paid Status",
    fill = "Was the loan paid?"
  ) +
  scale_fill_manual(
    values = c("#ef4123", "#002a4e")
  )
```



```{r}
loans_clean_viz %>% 
  group_by(purpose, loan_paid_flag) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  filter(loan_paid_flag == "Yes") %>% 
  arrange(prop) %>% 
  head(6)



loans_clean_viz %>% 
  filter(purpose %in% c("small_business", "renewable_energy", "other", 
                        "educational", "debt_consolidation")) %>% 
  group_by(purpose, loan_paid_flag) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 

  ggplot(aes(x = purpose, y = prop, fill = loan_paid_flag)) +
  geom_col() +
  coord_flip() +
  theme_minimal() +
  labs(
    x = "Purpose\n",
    y = "\nProportion",
    fill = "Was the loan paid?",
    title = "Proportion of Loans Paid by each Loan Purpose\n"
  ) +
  theme(
    text = element_text(size = 12)
  ) +
  scale_fill_manual(
    values = c("#ef4123", "#002a4e")
  )



loans_clean_viz %>% 
  group_by(purpose, loan_paid_flag) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = purpose, y = prop, fill = loan_paid_flag))+
  geom_col() +
  coord_flip() +
  theme_minimal() +
  labs(
    x = "Purpose\n",
    y = "\nProportion",
    fill = "Was the loan paid?",
    title = "Proportion of Loans Paid by each Loan Purpose\n"
  ) +
  theme(
    text = element_text(size = 12)
  ) +
  scale_fill_manual(
    values = c("#ef4123", "#002a4e")
  )


```

```{r}
loans_clean_viz %>% 
  group_by(loan_paid_flag) %>% 
  ggplot(aes(x = open_acc, y = stat(density), fill = loan_paid_flag)) +
  geom_histogram()+
  facet_wrap(~loan_paid_flag) 
```


```{r}
loans_clean_viz %>% 
  mutate(fico_change = last_fico_range_high - fico_range_high) %>% 
  group_by(loan_paid_flag) %>% 
  ggplot(aes(x = fico_change, y =stat(density), fill = loan_paid_flag)) +
  geom_histogram() +
  facet_wrap(~loan_paid_flag)
```



```{r}
states <- read_csv("data/state_names_info.csv")
```


```{r}
state_prop_paid <- loans_clean_viz %>% 
  group_by(addr_state, loan_paid_flag) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  filter(loan_paid_flag == "Yes") %>% 
  left_join(states, by = c("addr_state" = "state_abb")) %>% 
  select(state_name, prop, addr_state) %>% 
  rename(state = state_name)

state_prop_paid <- state_prop_paid[order(state_prop_paid$state),] 



plot_usmap(data = state_prop_paid,
           values = "prop",
           labels = TRUE) +
  scale_fill_gradient(low = "#f8d0c9",
                      high = "#ef4123",
                      name = NULL) +
  theme(
    legend.position = c(0.5, -0.01),
    legend.direction = "horizontal",
    legend.key.width = unit(0.5, "in"),
    legend.key.height = unit(0.2, "in"),
    legend.text = element_text(size = 15)
  )
```



```{r}
loans_clean_viz %>% 
  group_by(loan_amnt, loan_paid_flag) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  filter(n >= 5, loan_paid_flag == "Yes") %>% 
  ggplot(aes(x = loan_amnt, y = prop)) +
  geom_point(size = 2, colour = "#ef4123") +
  theme_minimal() +
  labs(
    x = "\nLoan Amount ($)",
    y = "Proportion\n",
    title = "Proportion of Loans Paid by Loan Amount\n"
  )+
  theme(
    text = element_text(size = 14)
  ) 
  
  
```

```{r}
loans_model_data %>% 
  group_by(loan_paid_flag) %>% 
  summarise(n = n())
```







